FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_GATEWAY_URL=http://localhost:3000
ARG VITE_FIREBASE_API_KEY=dummy
ARG VITE_FIREBASE_AUTH_DOMAIN=dummy.firebaseapp.com
ARG VITE_FIREBASE_PROJECT_ID=dummy
ARG VITE_FIREBASE_STORAGE_BUCKET=dummy.appspot.com
ARG VITE_FIREBASE_MESSAGING_SENDER_ID=000000000000
ARG VITE_FIREBASE_APP_ID=1:000000000000:web:0000000000000000000000

ENV VITE_GATEWAY_URL=$VITE_GATEWAY_URL
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID

COPY package*.json ./
RUN npm ci --ignore-scripts

COPY . .

RUN npm run build


FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production

EXPOSE 5173

CMD ["npm", "run", "preview"]