sonar.projectKey=ARSW2026-JDC_Traffic-Simulator-Frontend
sonar.organization=arsw2026-jdc
sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/test/**,node_modules/**
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info